/******************************************************************************
 * Module       : Ultrasonic Sensor
 * File Name    : ultrasonic_sensor.c
 * Author       : A7la Team :)
 * Created on   : 28/01/2025
 * Description  : Source file for the Ultrasonic Sensor driver
 *******************************************************************************/

#include "ultrasonic_sensor.h"  /* Include Ultrasonic Sensor header file */

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

static uint8 g_edgeTime = 0;  /* Counter to track the number of edges detected */
static uint16 g_highTime = 0;  /* Variable to store the high time of the echo pulse */

/*******************************************************************************
 *                       Functions Prototypes                                  *
 *******************************************************************************/

/* Static function to handle edge processing for the ultrasonic sensor */
static void Ultrasonic_edgeProcessing(void);

/*******************************************************************************
 *                       Functions Definitions                                 *
 *******************************************************************************/

/*
 * Description :
 * Initialize the ultrasonic sensor:
 * 1. Set up ICU configuration for echo pulse measurement.
 * 2. Initialize the ICU driver.
 * 3. Set the callback function for the ICU.
 * 4. Configure the trigger pin as an output.
 */
void Ultrasonic_init(void)
{
    /* Configure ICU for rising edge detection with F_CPU/8 prescaler */
    ICU_ConfigType ICU_Configurations = {F_CPU_8, RAISING};
    ICU_init(&ICU_Configurations);

    /* Set the callback function for the ICU */
    ICU_setCallBack(Ultrasonic_edgeProcessing);

    /* Set up the trigger pin as an output */
    GPIO_setupPinDirection(TRIGGER_PORT_CONNECTION, TRIGGER_PIN1, PIN_OUTPUT);
}

/*
 * Description :
 * Send a 10us trigger pulse to the ultrasonic sensor to start the measurement.
 */
static void Ultrasonic_Trigger(void)
{
    /* Set the trigger pin to high for 10us */
    GPIO_writePin(TRIGGER_PORT_CONNECTION, TRIGGER_PIN1, LOGIC_HIGH);
    _delay_us(10);

    /* Set the trigger pin back to low */
    GPIO_writePin(TRIGGER_PORT_CONNECTION, TRIGGER_PIN1, LOGIC_LOW);
}

/*
 * Description :
 * Measure the distance using the ultrasonic sensor:
 * 1. Send the trigger pulse to start the measurement.
 * 2. Use the ICU driver to measure the echo pulse duration.
 * 3. Calculate and return the distance in centimeters.
 * Returns     :
 * - The measured distance in centimeters.
 */
uint16 Ultrasonic_readDistance(void)
{
    /* Send the trigger pulse to start the measurement */
    Ultrasonic_Trigger();

    /* Calculate the distance in centimeters using the high time */
    return (g_highTime / 117.6) + 1;
}

/*
 * Description :
 * Callback function for the ICU driver to handle edge detection.
 * This function calculates the high time (echo pulse duration) generated by the ultrasonic sensor.
 */
static void Ultrasonic_edgeProcessing(void)
{
    g_edgeTime++;  /* Increment the edge counter */

    if (g_edgeTime == 1)
    {
        /*
         * First edge detected (rising edge):
         * 1. Clear the timer counter to start measurements from the first rising edge.
         * 2. Configure the ICU to detect the falling edge.
         */
        ICU_clearTimerValue();
        ICU_setEdgeDetectionType(FALLING);
    }
    else if (g_edgeTime == 2)
    {
        /*
         * Second edge detected (falling edge):
         * 1. Read the high time (echo pulse duration) from the ICU.
         * 2. Configure the ICU to detect the rising edge for the next measurement.
         * 3. Clear the timer counter for the next measurement.
         * 4. Reset the edge counter.
         */
        g_highTime = ICU_getInputCaptureValue();  /* Get the high time */
        ICU_setEdgeDetectionType(RAISING);        /* Detect rising edge next */
        ICU_clearTimerValue();                    /* Clear the timer counter */
        g_edgeTime = 0;                          /* Reset the edge counter */
    }
}
